### PR TITLE
Add CircleCi contexts

### PR DESCRIPTION
**Pull request by brikis98**
Looks like this repo was missed in our updates. @zackproser Any idea why?

### CODE REVIEW

**Review by yorinasub17 — APPROVED** [review]
LGTM!

**Comment by brikis98** [comment]
Thanks for the review! Merging now.

**Comment by zackproser** [comment]
> Looks like this repo was missed in our updates. @zackproser Any idea why?

Hey Jim, [this was the original list of repos targeted for programmatic context upgrades](https://docs.google.com/spreadsheets/d/10QFLh2vwTCusR5Zka7DmEoWQ-L-Vczldbglksg-aR88/edit#gid=0), and indeed this one was not a part of that list. It was a concatenation of some repo lists we had defined in one of our prototypes, in python, if memory serves. 

Let me know if we need another ticket cut for another batch of runs and I'll get that done.

**Comment by brikis98** [comment]
I think we should just add this repo to that list for possible future runs, and we're good to go... No need for any other run at the moment.

**Comment by zackproser** [comment]
> I think we should just add this repo to that list for possible future runs, and we're good to go... No need for any other run at the moment.

Roger - done!

**Comment by brikis98** [comment]
Thanks!

**Pull request merged**
