### PR TITLE
Update repo to work with TF 0.13

### PR DESCRIPTION
**Pull request by brikis98**
1. Update `required_version` to `0.12.26` everywhere.
1. Add pre-commit hooks.
1. Update version numbers in CI build.
1. Move license check earlier in tests so you don't have to wait for an AMI build to be told you forgot to set an env var.
1. Fix Ubuntu AMI names used in Packer builds so we aren't accidentally picking up some weirdo ubuntu-eks image.

### CODE REVIEW

**Comment by brikis98** [comment]
All the tests are successfully building AMIs with Packer and deploying them with Terraform, but something must not be booting correctly, as you get test failures where this error is repeated over and over:

```
TestInfluxDBSingleCluster/TestInfluxDBSingleClusterAmazonLinux 2020-10-15T14:50:43Z retry.go:72: Querying database
TestInfluxDBSingleCluster/TestInfluxDBSingleClusterAmazonLinux 2020-10-15T14:50:43Z test_helpers.go:77: Query failed: meta service unavailable
TestInfluxDBSingleCluster/TestInfluxDBSingleClusterAmazonLinux 2020-10-15T14:50:43Z retry.go:84: Querying database returned an error: meta service unavailable. Sleeping for 5s and will try again.
```

**Comment by brikis98** [comment]
I think this is because our Influx license expired. Messaged the Influx team in Slack to extend our license.

**Comment by brikis98** [comment]
Just fired up some nodes and confirmed the error in the logs:

```
Oct 16 08:52:10 ip-172-31-8-211 influxd-meta[1781]: ts=2020-10-16T08:52:10.915923Z lvl=error msg="LICENSE IS INVALID OR CANNOT BE FOUND" log_id=0Pt9aDRG000 service=licensing error="open /tmp/influx-enterp
```

**Comment by brikis98** [comment]
OK, our license has been renewed, and tests are passing! This is ready for review.

**Review by robmorgan — APPROVED** [review]
LGTM

**Pull request merged**
